# Configuration for Label Actions - https://github.com/dessant/label-actions

# Specify actions for issues and pull requests
actions:
  # Actions taken when the `heated` label is added
  "Type: Support request":
    # Post a comment
    comment: |-
      Hello @{issue-author},  
      It seems like you ask for support with the bot, the API or similar.  
        
      Sadly the issue section isn't the best place to seek for support.  
      We recommend to you, to make sure you've read the [wiki](/Andre601/PurrBot/wiki) to make sure your question isn't answered there.  
      If you still need support, join our [Discord](https://purrbot.site/discord).
    close: true
    # Lock the thread
    lock: false
    # Set a lock reason, such as `off-topic`, `too heated`, `resolved` or `spam`
    lockReason: "too heated"
  # Actions taken when the `heated` label is removed
  "Type: Dublicate":
    comment: |-
      This issue (or a similar one) does already exist.  
      Please make sure you checked the Issue-page for already existing ones, before creating an issue.
    close: true
  "Problem: Need more info":
    comment: |-
      Hello @{issue-author},
      Your reported bug/problem seems to lack proper information.  
      We can't provide the right solution if we don't have enough information.  
        
      Please follow these steps to provide more information:  
      - Give an up to date debug report (Run `.debug` and provide the generated link)
      - Make sure the bot has the required permissions  
      - Make sure you've checked the wiki for known answers and solutions
    
# Optionally, specify configuration settings just for issues
issues:
  actions:
    feature:
      # Post a comment, `{issue-author}` is an optional placeholder
      comment: >
        :wave: @{issue-author}, please use our idea board to request new features.
      # Close the issue
      close: true
    -wontfix:
      # Reopen the issue
      open: true

# Optionally, specify configuration settings just for pull requests
pulls:
  actions:
    pizzazz:
      comment: >
        ![](https://i.imgur.com/WuduJNk.jpg)

# Limit to only `issues` or `pulls`
only: issues

# Repository to extend settings from
# _extends: repo
