# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: "Type: Support request"

# Comment to post on issues marked as support requests, `{issue-author}` is an
# optional placeholder. Set to `false` to disable
supportComment: >
  Hello @{issue-author},  
  We're glad that you're seeking out for support with our bot.  
  Sadly, the GitHub-issues aren't the best places, to ask for such things.  
    
  For proper support, please join our [Discord](https://discord.gg/NB7AFqn) and make sure you've read the [wiki](/Andre601/PurrBot/wiki)

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: false

# Assign `off-topic` as the reason for locking. Set to `false` to disable
setLockReason: true

# Repository to extend settings from
# _extends: repo
