blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://purrbot.site/discord
    about: Please join our Discord for support with *Purr*
  - name: Wiki
    url: https://docs.purrbot.site/bot
    about: Make sure to check our wiki before asking questions.
  - name: Questions and Suggestsions
    url: https://github.com/purrbot-site/PurrBot/discussions
    about: Please ask questions or share ideas in our Discussions.
