name: Comment

on:
  issues:
    types:
    - labeled
    - unlabeled
  pull_request:
    types:
    - labeled
    - unlabeled

jobs:
  give_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Send Issue/Pull request comment
      uses: peaceiris/actions-label-commenter@v1.4.0-0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
