name: Label Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  label:
    if: '${{ github.head_ref }} == l10n_master'
    runs-on: ubuntu-latest
    steps:
      - name: Label Pull request
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
